# Generated by Django 5.0.5 on 2024-05-07 08:28

import api.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Ticket",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.TextField(verbose_name="title")),
                ("description", models.TextField(verbose_name="description")),
                ("phone", models.TextField(verbose_name="phone")),
                (
                    "status",
                    models.TextField(
                        choices=[
                            ("created", "created"),
                            ("in work", "in work"),
                            ("done", "done"),
                        ],
                        verbose_name="status",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        blank=True,
                        default=api.models.get_datetime,
                        null=True,
                        verbose_name="created",
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
